apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mean-eks-demo
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 10
    volumeSize: 80
    ssh:
      allow: true #